apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: leaderboard.baq.emf-informatique.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jpo-leaderboard
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpo-leaderboard
  labels:
    app: jpo-leaderboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jpo-leaderboard
  template:
    metadata:
      labels:
        app: jpo-leaderboard
    spec:
      imagePullSecrets:
        - name: acr-pull
      containers:
        - name: app
          image: m324demoacrqba.azurecr.io/jpo-leaderboard:sha-b3f769c47ff87042940c371cac3930fdf791c32c
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jpo-leaderboard
  labels:
    app: jpo-leaderboard
spec:
  selector:
    app: jpo-leaderboard
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
