apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpo-leaderboard
  namespace: team-a
  labels:
    app: jpo-leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpo-leaderboard
  template:
    metadata:
      labels:
        app: jpo-leaderboard
    spec:
      imagePullSecrets:
        - name: acr-pull
      containers:
        - name: app
          image: m324demoacrqba.azurecr.io/jpo-leaderboard:sha-ccedf5cd8b12d843ec7f93e621e7c1ddd3f640f6
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jpo-leaderboard
  namespace: team-a
  labels:
    app: jpo-leaderboard
spec:
  selector:
    app: jpo-leaderboard
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP